kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 32400
    hostPort: 32400
  extraMounts:
  - hostPath: /etc/ssl/certs
    containerPath: /etc/ssl/certs
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        oidc-issuer-url: https://dex.dex.svc:32400
        oidc-client-id: public-postman
        oidc-ca-file: /etc/ssl/certs/openid-ca3.pem
        oidc-username-claim: email
        oidc-groups-claim: groups
- role: worker
- role: worker
