apiVersion: v1
kind: Service
metadata:
  name: dummy-svc
  namespace: default
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
