apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-blue-team-nginx
  namespace: nginx
subjects:
- kind: Group
  name: blue-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-pods-nginx
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-red-team-dex
  namespace: dex
subjects:
- kind: Group
  name: red-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-pods
  apiGroup: rbac.authorization.k8s.io

