apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: local-path-storage
  name: read-pods-local-path-storage
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-user2-local-path-storage
  namespace: local-path-storage
subjects:
- kind: User
  name: oagarwal1998@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: read-pods-local-path-storage
  apiGroup: rbac.authorization.k8s.io
